openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Homeset

#
# Paths
#
paths:
  #
  # API
  #

  # Users

  /api/v1/users:
    # Create user
    post:
      summary: Creates a new user.
      operationId: APICreateUser
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref:  '#/components/schemas/Error'

  #
  # Pages
  #

  /:
    get:
      summary: Index page
      operationId: PageIndex
      tags:
        - pages
      responses:
        '200':
          description: Index page

  /login:
    get:
      summary: Login page
      operationId: PageLogin
      responses:
        '200':
          description: Login page


#
# Components
#
components:
  schemas:
    #
    # Types
    #
    Error:
      required:
        - status_code
        - error
      properties:
        status_code:
          type: integer
        error:
          type: string

    User:
      required:
        - username
      properties:
        username:
          type: string


    #
    # Requests/Responses
    #
    CreateUserRequest:
      required:
        - username
        - password
      properties:
        username:
          type: string
          minLength: 4
          maxLength: 128
        password:
          type: string
          minLength: 4
          maxLength: 128

    CreateUserResponse:
      required:
        - user
      properties:
        user:
          $ref: '#/components/schemas/User'