// Code generated by http://github.com/gojuno/minimock (v3.4.0). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/oustrix/homeset/internal/models"
	"github.com/oustrix/homeset/internal/store/dto"
)

// GetUserRepositoryMock implements mm_users.GetUserRepository
type GetUserRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetUser          func(ctx context.Context, input dto.GetUserInput) (u1 models.User, err error)
	funcGetUserOrigin    string
	inspectFuncGetUser   func(ctx context.Context, input dto.GetUserInput)
	afterGetUserCounter  uint64
	beforeGetUserCounter uint64
	GetUserMock          mGetUserRepositoryMockGetUser
}

// NewGetUserRepositoryMock returns a mock for mm_users.GetUserRepository
func NewGetUserRepositoryMock(t minimock.Tester) *GetUserRepositoryMock {
	m := &GetUserRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetUserMock = mGetUserRepositoryMockGetUser{mock: m}
	m.GetUserMock.callArgs = []*GetUserRepositoryMockGetUserParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mGetUserRepositoryMockGetUser struct {
	optional           bool
	mock               *GetUserRepositoryMock
	defaultExpectation *GetUserRepositoryMockGetUserExpectation
	expectations       []*GetUserRepositoryMockGetUserExpectation

	callArgs []*GetUserRepositoryMockGetUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// GetUserRepositoryMockGetUserExpectation specifies expectation struct of the GetUserRepository.GetUser
type GetUserRepositoryMockGetUserExpectation struct {
	mock               *GetUserRepositoryMock
	params             *GetUserRepositoryMockGetUserParams
	paramPtrs          *GetUserRepositoryMockGetUserParamPtrs
	expectationOrigins GetUserRepositoryMockGetUserExpectationOrigins
	results            *GetUserRepositoryMockGetUserResults
	returnOrigin       string
	Counter            uint64
}

// GetUserRepositoryMockGetUserParams contains parameters of the GetUserRepository.GetUser
type GetUserRepositoryMockGetUserParams struct {
	ctx   context.Context
	input dto.GetUserInput
}

// GetUserRepositoryMockGetUserParamPtrs contains pointers to parameters of the GetUserRepository.GetUser
type GetUserRepositoryMockGetUserParamPtrs struct {
	ctx   *context.Context
	input *dto.GetUserInput
}

// GetUserRepositoryMockGetUserResults contains results of the GetUserRepository.GetUser
type GetUserRepositoryMockGetUserResults struct {
	u1  models.User
	err error
}

// GetUserRepositoryMockGetUserOrigins contains origins of expectations of the GetUserRepository.GetUser
type GetUserRepositoryMockGetUserExpectationOrigins struct {
	origin      string
	originCtx   string
	originInput string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetUser *mGetUserRepositoryMockGetUser) Optional() *mGetUserRepositoryMockGetUser {
	mmGetUser.optional = true
	return mmGetUser
}

// Expect sets up expected params for GetUserRepository.GetUser
func (mmGetUser *mGetUserRepositoryMockGetUser) Expect(ctx context.Context, input dto.GetUserInput) *mGetUserRepositoryMockGetUser {
	if mmGetUser.mock.funcGetUser != nil {
		mmGetUser.mock.t.Fatalf("GetUserRepositoryMock.GetUser mock is already set by Set")
	}

	if mmGetUser.defaultExpectation == nil {
		mmGetUser.defaultExpectation = &GetUserRepositoryMockGetUserExpectation{}
	}

	if mmGetUser.defaultExpectation.paramPtrs != nil {
		mmGetUser.mock.t.Fatalf("GetUserRepositoryMock.GetUser mock is already set by ExpectParams functions")
	}

	mmGetUser.defaultExpectation.params = &GetUserRepositoryMockGetUserParams{ctx, input}
	mmGetUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetUser.expectations {
		if minimock.Equal(e.params, mmGetUser.defaultExpectation.params) {
			mmGetUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetUser.defaultExpectation.params)
		}
	}

	return mmGetUser
}

// ExpectCtxParam1 sets up expected param ctx for GetUserRepository.GetUser
func (mmGetUser *mGetUserRepositoryMockGetUser) ExpectCtxParam1(ctx context.Context) *mGetUserRepositoryMockGetUser {
	if mmGetUser.mock.funcGetUser != nil {
		mmGetUser.mock.t.Fatalf("GetUserRepositoryMock.GetUser mock is already set by Set")
	}

	if mmGetUser.defaultExpectation == nil {
		mmGetUser.defaultExpectation = &GetUserRepositoryMockGetUserExpectation{}
	}

	if mmGetUser.defaultExpectation.params != nil {
		mmGetUser.mock.t.Fatalf("GetUserRepositoryMock.GetUser mock is already set by Expect")
	}

	if mmGetUser.defaultExpectation.paramPtrs == nil {
		mmGetUser.defaultExpectation.paramPtrs = &GetUserRepositoryMockGetUserParamPtrs{}
	}
	mmGetUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetUser
}

// ExpectInputParam2 sets up expected param input for GetUserRepository.GetUser
func (mmGetUser *mGetUserRepositoryMockGetUser) ExpectInputParam2(input dto.GetUserInput) *mGetUserRepositoryMockGetUser {
	if mmGetUser.mock.funcGetUser != nil {
		mmGetUser.mock.t.Fatalf("GetUserRepositoryMock.GetUser mock is already set by Set")
	}

	if mmGetUser.defaultExpectation == nil {
		mmGetUser.defaultExpectation = &GetUserRepositoryMockGetUserExpectation{}
	}

	if mmGetUser.defaultExpectation.params != nil {
		mmGetUser.mock.t.Fatalf("GetUserRepositoryMock.GetUser mock is already set by Expect")
	}

	if mmGetUser.defaultExpectation.paramPtrs == nil {
		mmGetUser.defaultExpectation.paramPtrs = &GetUserRepositoryMockGetUserParamPtrs{}
	}
	mmGetUser.defaultExpectation.paramPtrs.input = &input
	mmGetUser.defaultExpectation.expectationOrigins.originInput = minimock.CallerInfo(1)

	return mmGetUser
}

// Inspect accepts an inspector function that has same arguments as the GetUserRepository.GetUser
func (mmGetUser *mGetUserRepositoryMockGetUser) Inspect(f func(ctx context.Context, input dto.GetUserInput)) *mGetUserRepositoryMockGetUser {
	if mmGetUser.mock.inspectFuncGetUser != nil {
		mmGetUser.mock.t.Fatalf("Inspect function is already set for GetUserRepositoryMock.GetUser")
	}

	mmGetUser.mock.inspectFuncGetUser = f

	return mmGetUser
}

// Return sets up results that will be returned by GetUserRepository.GetUser
func (mmGetUser *mGetUserRepositoryMockGetUser) Return(u1 models.User, err error) *GetUserRepositoryMock {
	if mmGetUser.mock.funcGetUser != nil {
		mmGetUser.mock.t.Fatalf("GetUserRepositoryMock.GetUser mock is already set by Set")
	}

	if mmGetUser.defaultExpectation == nil {
		mmGetUser.defaultExpectation = &GetUserRepositoryMockGetUserExpectation{mock: mmGetUser.mock}
	}
	mmGetUser.defaultExpectation.results = &GetUserRepositoryMockGetUserResults{u1, err}
	mmGetUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetUser.mock
}

// Set uses given function f to mock the GetUserRepository.GetUser method
func (mmGetUser *mGetUserRepositoryMockGetUser) Set(f func(ctx context.Context, input dto.GetUserInput) (u1 models.User, err error)) *GetUserRepositoryMock {
	if mmGetUser.defaultExpectation != nil {
		mmGetUser.mock.t.Fatalf("Default expectation is already set for the GetUserRepository.GetUser method")
	}

	if len(mmGetUser.expectations) > 0 {
		mmGetUser.mock.t.Fatalf("Some expectations are already set for the GetUserRepository.GetUser method")
	}

	mmGetUser.mock.funcGetUser = f
	mmGetUser.mock.funcGetUserOrigin = minimock.CallerInfo(1)
	return mmGetUser.mock
}

// When sets expectation for the GetUserRepository.GetUser which will trigger the result defined by the following
// Then helper
func (mmGetUser *mGetUserRepositoryMockGetUser) When(ctx context.Context, input dto.GetUserInput) *GetUserRepositoryMockGetUserExpectation {
	if mmGetUser.mock.funcGetUser != nil {
		mmGetUser.mock.t.Fatalf("GetUserRepositoryMock.GetUser mock is already set by Set")
	}

	expectation := &GetUserRepositoryMockGetUserExpectation{
		mock:               mmGetUser.mock,
		params:             &GetUserRepositoryMockGetUserParams{ctx, input},
		expectationOrigins: GetUserRepositoryMockGetUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetUser.expectations = append(mmGetUser.expectations, expectation)
	return expectation
}

// Then sets up GetUserRepository.GetUser return parameters for the expectation previously defined by the When method
func (e *GetUserRepositoryMockGetUserExpectation) Then(u1 models.User, err error) *GetUserRepositoryMock {
	e.results = &GetUserRepositoryMockGetUserResults{u1, err}
	return e.mock
}

// Times sets number of times GetUserRepository.GetUser should be invoked
func (mmGetUser *mGetUserRepositoryMockGetUser) Times(n uint64) *mGetUserRepositoryMockGetUser {
	if n == 0 {
		mmGetUser.mock.t.Fatalf("Times of GetUserRepositoryMock.GetUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetUser.expectedInvocations, n)
	mmGetUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetUser
}

func (mmGetUser *mGetUserRepositoryMockGetUser) invocationsDone() bool {
	if len(mmGetUser.expectations) == 0 && mmGetUser.defaultExpectation == nil && mmGetUser.mock.funcGetUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetUser.mock.afterGetUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetUser implements mm_users.GetUserRepository
func (mmGetUser *GetUserRepositoryMock) GetUser(ctx context.Context, input dto.GetUserInput) (u1 models.User, err error) {
	mm_atomic.AddUint64(&mmGetUser.beforeGetUserCounter, 1)
	defer mm_atomic.AddUint64(&mmGetUser.afterGetUserCounter, 1)

	mmGetUser.t.Helper()

	if mmGetUser.inspectFuncGetUser != nil {
		mmGetUser.inspectFuncGetUser(ctx, input)
	}

	mm_params := GetUserRepositoryMockGetUserParams{ctx, input}

	// Record call args
	mmGetUser.GetUserMock.mutex.Lock()
	mmGetUser.GetUserMock.callArgs = append(mmGetUser.GetUserMock.callArgs, &mm_params)
	mmGetUser.GetUserMock.mutex.Unlock()

	for _, e := range mmGetUser.GetUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.u1, e.results.err
		}
	}

	if mmGetUser.GetUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetUser.GetUserMock.defaultExpectation.Counter, 1)
		mm_want := mmGetUser.GetUserMock.defaultExpectation.params
		mm_want_ptrs := mmGetUser.GetUserMock.defaultExpectation.paramPtrs

		mm_got := GetUserRepositoryMockGetUserParams{ctx, input}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetUser.t.Errorf("GetUserRepositoryMock.GetUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUser.GetUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.input != nil && !minimock.Equal(*mm_want_ptrs.input, mm_got.input) {
				mmGetUser.t.Errorf("GetUserRepositoryMock.GetUser got unexpected parameter input, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUser.GetUserMock.defaultExpectation.expectationOrigins.originInput, *mm_want_ptrs.input, mm_got.input, minimock.Diff(*mm_want_ptrs.input, mm_got.input))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetUser.t.Errorf("GetUserRepositoryMock.GetUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetUser.GetUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetUser.GetUserMock.defaultExpectation.results
		if mm_results == nil {
			mmGetUser.t.Fatal("No results are set for the GetUserRepositoryMock.GetUser")
		}
		return (*mm_results).u1, (*mm_results).err
	}
	if mmGetUser.funcGetUser != nil {
		return mmGetUser.funcGetUser(ctx, input)
	}
	mmGetUser.t.Fatalf("Unexpected call to GetUserRepositoryMock.GetUser. %v %v", ctx, input)
	return
}

// GetUserAfterCounter returns a count of finished GetUserRepositoryMock.GetUser invocations
func (mmGetUser *GetUserRepositoryMock) GetUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUser.afterGetUserCounter)
}

// GetUserBeforeCounter returns a count of GetUserRepositoryMock.GetUser invocations
func (mmGetUser *GetUserRepositoryMock) GetUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUser.beforeGetUserCounter)
}

// Calls returns a list of arguments used in each call to GetUserRepositoryMock.GetUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetUser *mGetUserRepositoryMockGetUser) Calls() []*GetUserRepositoryMockGetUserParams {
	mmGetUser.mutex.RLock()

	argCopy := make([]*GetUserRepositoryMockGetUserParams, len(mmGetUser.callArgs))
	copy(argCopy, mmGetUser.callArgs)

	mmGetUser.mutex.RUnlock()

	return argCopy
}

// MinimockGetUserDone returns true if the count of the GetUser invocations corresponds
// the number of defined expectations
func (m *GetUserRepositoryMock) MinimockGetUserDone() bool {
	if m.GetUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetUserMock.invocationsDone()
}

// MinimockGetUserInspect logs each unmet expectation
func (m *GetUserRepositoryMock) MinimockGetUserInspect() {
	for _, e := range m.GetUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to GetUserRepositoryMock.GetUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetUserCounter := mm_atomic.LoadUint64(&m.afterGetUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetUserMock.defaultExpectation != nil && afterGetUserCounter < 1 {
		if m.GetUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to GetUserRepositoryMock.GetUser at\n%s", m.GetUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to GetUserRepositoryMock.GetUser at\n%s with params: %#v", m.GetUserMock.defaultExpectation.expectationOrigins.origin, *m.GetUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetUser != nil && afterGetUserCounter < 1 {
		m.t.Errorf("Expected call to GetUserRepositoryMock.GetUser at\n%s", m.funcGetUserOrigin)
	}

	if !m.GetUserMock.invocationsDone() && afterGetUserCounter > 0 {
		m.t.Errorf("Expected %d calls to GetUserRepositoryMock.GetUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetUserMock.expectedInvocations), m.GetUserMock.expectedInvocationsOrigin, afterGetUserCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *GetUserRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetUserInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *GetUserRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *GetUserRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetUserDone()
}
