name: Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go 1.23.0
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - name: Install dependencies
        run: go get .
      - name: Build
        run: make build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go 1.23.0
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - name: Install dependencies
        run: go get .
      - name: Test
        run: make test